### ISSUE TITLE
Program cannot run

### ISSUE THREAD

**Issue by kkkvito** [yule-BUAA/LEGNN#1]
Hi! I really like this work. The paper is very precise and readable. But when I tried to run the code, there was a problem.The system reported the following error:
        RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
        Thank you for responding to my question.

**Comment by yule-BUAA** [comment]
> ```
>     Hi! I really like this work. The paper is very precise and readable. But when I tried to run the code, there was a problem.The system reported the following error:
>     RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
>     Thank you for responding to my question.
> ```

Hi! Thanks for your interest in our work. 
I can run the code without any issues. Could you please provide more specific details about the error you encountered?
Additionally, please ensure that the versions of PyTorch and DGL are correct.

**Comment by kkkvito** [comment]
> > ```
> >     Hi! I really like this work. The paper is very precise and readable. But when I tried to run the code, there was a problem.The system reported the following error:
> >     RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
> >     Thank you for responding to my question.
> > ```
> 
> Hi! Thanks for your interest in our work. I can run the code without any issues. Could you please provide more specific details about the error you encountered? Additionally, please ensure that the versions of PyTorch and DGL are correct.

Hello, Mr. Yu. I originally wanted to install PyTorch 1.8.1, but I saw the PyTorch-Geometric and DGL's official website saying that they require that at least PyTorch 1.12 is installed.So,I installed PyTorch 1.13.1+cu117,PyTorch-Geometric 2.2.0 and DGL 1.0.2 .Where can I download an older version of DGL and PyG?Could you upload REQUIREMENT ? Umm,but I don't feel like it's the package’s problem . The system reported an error saying that the index and tensor should be placed on the same device. I just don't know how to change the code.Thanks for your help!

**Comment by yule-BUAA** [comment]
> 



> > > ```
> > >     Hi! I really like this work. The paper is very precise and readable. But when I tried to run the code, there was a problem.The system reported the following error:
> > >     RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
> > >     Thank you for responding to my question.
> > > ```
> > 
> > 
> > Hi! Thanks for your interest in our work. I can run the code without any issues. Could you please provide more specific details about the error you encountered? Additionally, please ensure that the versions of PyTorch and DGL are correct.
> 
> Hello, Mr. Yu. I originally wanted to install PyTorch 1.8.1, but I saw the PyTorch-Geometric and DGL's official website saying that they require that at least PyTorch 1.12 is installed.So,I installed PyTorch 1.13.1+cu117,PyTorch-Geometric 2.2.0 and DGL 1.0.2 .Where can I download an older version of DGL and PyG?Could you upload REQUIREMENT ? Umm,but I don't feel like it's the package’s problem . The system reported an error saying that the index and tensor should be placed on the same device. I just don't know how to change the code.Thanks for your help!

It doesn’t seem to be a version issue since you’re using a newer version, but please ensure that the packages are all GPU versions. 
For the mentioned error, one possible solution is to put the index on the CPU by `indices = indices.to(‘cpu’)`
, and then use `indexed_tensor[indices]` for the indexing operation. 
If there are still problems, you can provide which file you are running and paste the error information.

**Comment by kkkvito** [comment]
I am running train_full_batch_LEGNN.py.
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
**Traceback (most recent call last):
  File "D:\MYmodel\LEGNN-master\train_LEGNN\train_full_batch_LEGNN.py", line 120, in <module>
    train_graph = add_connections_between_labels_nodes(graph, labels, train_truth_idx)**

Original source:
 **# compute the loss for train_predict_idx nodes, so get train predict and truth idx based on train_idx**

           `for epoch in range(args['epochs']):

                    train_predict_idx, train_truth_idx = get_train_predict_truth_idx(train_idx, args['train_select_rate'])

                    train_graph = add_connections_between_labels_nodes(graph, labels, train_truth_idx)

                    train_loss, train_accuracy = train_model(model, train_graph, copy.deepcopy(input_features), labels, train_predict_idx, args['predict_category'], loss_func,
                                                     optimizer, scheduler, dataset_name=args['dataset'])

                    val_loss, val_accuracy, test_loss, test_accuracy = evaluate_model(model, evaluate_graph, copy.deepcopy(input_features), labels, valid_idx, test_idx,
                                                                              args['predict_category'], loss_func, dataset_name=args['dataset'])

                    logger.info(
                f'Epoch: {epoch + 1}, learning rate: {optimizer.param_groups[0]["lr"]}, train loss: {train_loss:.4f}, accuracy {train_accuracy:.4f}, '
                f'valid loss: {val_loss:.4f}, accuracy {val_accuracy:.4f}, test loss: {test_loss:.4f}, accuracy {test_accuracy:.4f}')

                    early_stop = early_stopping.step([('accuracy', val_accuracy, True)], model)
                    if early_stop:
                              break`

**File "D:\MYmodel\LEGNN-master\utils\utils.py", line 244, in add_connections_between_labels_nodes
    original_node_idx = node_idx[labels[node_idx] == label_idx].to('cpu')**
Original source:
**#add connections between training nodes and label nodes**
**#Tensor of original node idx**

           `def add_connections_between_labels_nodes(graph: dgl.DGLHeteroGraph, labels: torch.Tensor, node_idx: torch.Tensor):
                   graph_copy = graph.clone()
                   src_indices_list, dst_indices_list = [], []
                   for label_idx in labels.unique():
                        original_node_idx = node_idx[labels[node_idx] == label_idx].to(labels.device)
                        if len(original_node_idx) > 0:
    	                     src_indices_list.append(original_node_idx)
    	                     dst_indices_list.append(label_idx.repeat(len(original_node_idx)))
                   src_indices = torch.cat(src_indices_list, dim=0)
                   dst_indices = torch.cat(dst_indices_list, dim=0)
                   graph_copy.add_edges(src_indices, dst_indices, etype=('node', 'node_label', 'label'))
                   graph_copy.add_edges(dst_indices, src_indices, etype=('label', 'rev_node_label', 'node'))
                   return graph_copy`

**Comment by yule-BUAA** [comment]
> 

Indeed, this error didn't occur when I ran the code. There are some things you can try.

Firstly, please set the 'cuda' parameter in args to -1, and run the code on the CPU to see whether it works. If it works well, then check the following:

When I run the code, `node_idx` is on the CPU, and `labels` should be on the GPU, and using `labels[node_idx]` would be fine. `original_node_idx ` is on the same GPU as `labels`. `graph_copy `, `src_indices `, and `dst_indices ` are all on the same GPU as well. Please check these when you run the code and see if there are any differences.

**Comment by kkkvito** [comment]
> > 
> 
> Indeed, this error didn't occur when I ran the code. There are some things you can try.
> 
> Firstly, please set the 'cuda' parameter in args to -1, and run the code on the CPU to see whether it works. If it works well, then check the following:
> 
> When I run the code, `node_idx` is on the CPU, and `labels` should be on the GPU, and using `labels[node_idx]` would be fine. `original_node_idx ` is on the same GPU as `labels`. `graph_copy `, `src_indices `, and `dst_indices ` are all on the same GPU as well. Please check these when you run the code and see if there are any differences.

I later asked others and finally found out which index was wrong. Thank you.
